### ISSUE TITLE
error in  node-js  (version 1) : Cannot find module 'jalali-date'

### ISSUE THREAD

**Issue by hamid** [arashm/JDate#12]
Hi.
i update to version 1  but the node gave me an error  when I use `require('jalali-date');`
_`Cannot find module 'jalali-date'`_
so i have to   downgrade  to version 0.1.1 
please fix it in node-js.

**Comment by arashm** [comment]
Sorry I didn't notice this. I fixed it on `1.0.2`. Let me know if you got any other issue. Thank you.
