### ISSUE TITLE
wrong leap for 1403/12

### ISSUE THREAD

**Issue by mshahbazi** [arashm/JDate#15]
Salam,
Thanks for the great work.
Something is wrong with `leapPersian`. 1403 is leap but the function returns false.

**Comment by arashm** [comment]
hmm... I think it's an edge case in the algorithm. Have to rewrite it using another one. Will work on later this week. Thanks for the report.

**Comment by mshahbazi** [comment]
Thank you so much.

I also suggest removing the following from `daysInMonth`, since the month is zero-based
```
    else if (calcedMonth === 0) {
       calcedMonth = 12;
    } 

```
