### ISSUE TITLE
Gregorian to Jalali

### ISSUE THREAD

**Issue by dlbaran** [arashm/JDate#26]
Hi,
I need to display the date stored in the Gregorian database in Jalali. How can I do this using your library? My codes are as follows:

elseif($column_type_lookup[$column_name] == 'date'){ //date with format MM/DD/YYYY
					if(!empty($row[$column_name]) && ($row[$column_name] != '0000-00-00')){
						$form_data[$i][$j]  = date('M d, Y',strtotime($row[$column_name]));
					}

					if($column_name == 'date_created' || $column_name == 'date_updated'){
						$form_data[$i][$j] = mf_short_relative_date($row[$column_name]);
					}
				}elseif($column_type_lookup[$column_name] == 'europe_date'){ //date with format DD/MM/YYYY
					
					if(!empty($row[$column_name]) && ($row[$column_name] != '0000-00-00')){
						$form_data[$i][$j]  = date('d M Y',strtotime($row[$column_name]));
					}
				}

**Comment by arashm** [comment]
I don't understand what is this. PHP?
