### ISSUE TITLE
Incorrect Leap Year Calculation and Days in Month for Non-Leap Years

### ISSUE THREAD

**Issue by amin-s81** [arashm/JDate#37]
The JDate class appears to have issues with calculating leap years and the number of days in a month for non-leap years.

### Expected Behavior:
`JDate.isLeapYear(1403)` should return false.
`JDate.daysInMonth(1403, 12)` should return 30.

### Actual Behavior:
`JDate.isLeapYear(1403)` returns true.
`JDate.daysInMonth(1403, 12)` returns 29.

**Comment by arashm** [comment]
This should be fixed in v1.1.5. Let me know if you have any issues with it.
